#!/usr/bin/env python3
"""Writes 8b8/params.js: the 8b8's settings and its factory sounds, for the 8b8 Link view.

Reads them from a checkout of keyandcableco/8bit8asterd, its generate.py being the single source
of truth for both. Run it again whenever that file's PARAMS or PRESETS change:

    python3 tools/8b8-params.py ../8bit8asterd

The 8b8 reports its layout as LAYOUT:<hex>,<count> when asked for a dump. The view only names
settings and loads sounds when that matches the layout written here, so a stale copy is never
misread as the new one.
"""
import json, os, sys

src = os.path.abspath(sys.argv[1] if len(sys.argv) > 1 else "../8bit8asterd")
sys.path.insert(0, src)
import generate as g  # noqa: E402

def rng(p):
    if "options" in p: return 0, len(p["options"]) - 1
    if p.get("kind") == "toggle": return 0, 1
    return p["min"], p["max"]

params = []
for p in g.PARAMS:
    lo, hi = rng(p)
    row = {"key": p["key"], "group": p["group"], "label": p["label"], "min": lo, "max": hi, "default": p["default"]}
    if "options" in p: row["options"] = p["options"]
    params.append(row)
keys = [p["key"] for p in g.PARAMS]
defaults = [p["default"] for p in g.PARAMS]
sounds = {}
for name, over in g.PRESETS.items():
    vals = list(defaults)
    for k, v in over.items(): vals[keys.index(k)] = v
    sounds[name] = vals

with open(os.path.join(src, "parameters.h")) as f:
    layout = next(l.split()[2] for l in f if l.startswith("#define PARAM_LAYOUT_VERSION"))
layout = format(int(layout, 16), "X")

out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "8b8", "params.js")
with open(out, "w") as f:
    f.write("// GENERATED by tools/8b8-params.py from keyandcableco/8bit8asterd's generate.py. Do not edit by hand.\n")
    f.write("// The 8b8's settings in its own order (the index is the number P:<i>:<v> takes), and its factory sounds.\n")
    f.write(f'export const LAYOUT_8B8 = "{layout},{len(params)}";\n')
    f.write("export const PARAMS_8B8 = [\n" + ",\n".join("  " + json.dumps(p, ensure_ascii=False) for p in params) + "\n];\n")
    f.write("export const SOUNDS_8B8 = {\n" + ",\n".join(f"  {json.dumps(n)}: {json.dumps(v)}" for n, v in sounds.items()) + "\n};\n")
print("wrote", os.path.relpath(out), "layout", layout, len(params), "settings,", len(sounds), "sounds")
